version: '3.8'

services:
  backend:
    image: yassinsiouda/motivo-server-back:latest
    build: 
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5002:5002"
      - "8765:8765"
    env_file:
      - .env
    volumes:
      - ./metamotivo-S-1-datasets:/app/metamotivo-S-1-datasets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: yassinsiouda/motivo-client-front:latest
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

